import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { ProjectReviews } from "@/components/project-reviews";
import { ProjectDetailModal } from "@/components/project-detail-modal";
import { ProjectReviewsManager } from "@/components/admin/ProjectReviewsManager";
import { formatProjectCompletion } from "@/lib/project-date";
import type { PublicProject } from "@/types/project";
vi.mock("@/lib/project-reviews", () => ({ fetchProjectReviews: vi.fn(), submitProjectReview: vi.fn() }));
vi.mock("@/lib/admin/api", () => ({ fetchAdminProjectReviews: vi.fn(), setAdminReviewVisibility: vi.fn(), deleteAdminReview: vi.fn() }));
import { fetchProjectReviews, submitProjectReview } from "@/lib/project-reviews";
import { fetchAdminProjectReviews, setAdminReviewVisibility, deleteAdminReview } from "@/lib/admin/api";
const review = { id: "review-1", projectId: "project-1", reviewerName: "Visitor", rating: 5, reviewText: "Very helpful installation team.", createdAt: "2026-09-15T12:00:00Z" };
const empty = { reviews: [], reviewCount: 0, averageRating: null, hasMore: false };
beforeEach(() => { vi.resetAllMocks(); vi.mocked(fetchProjectReviews).mockResolvedValue(empty); });
afterEach(cleanup);
describe("project reviews", () => {
 it("shows the honest empty state and labelled required inputs", async () => {
  render(<ProjectReviews projectId="project-1" />);
  expect(await screen.findByText(/No reviews yet/)).toBeDefined();
  expect(screen.getByLabelText("Your Name (required)")).toBeDefined();
  expect(screen.getAllByRole("radio")).toHaveLength(5);
  expect(screen.getByLabelText("Review (required)")).toBeDefined();
 });
 it("validates name, rating, trimmed review length and backend errors", async () => {
  render(<ProjectReviews projectId="project-1" />);
  fireEvent.click(screen.getByRole("button", { name: "Submit Review" }));
  expect(screen.getByRole("alert").textContent).toMatch(/Enter your name/);
  fireEvent.change(screen.getByLabelText("Your Name (required)"), { target: { value: "Visitor" } });
  fireEvent.click(screen.getByRole("button", { name: "Submit Review" }));
  expect(screen.getByRole("alert").textContent).toMatch(/Choose a rating/);
  fireEvent.click(screen.getByRole("radio", { name: "5 stars" }));
  fireEvent.change(screen.getByLabelText("Review (required)"), { target: { value: " short " } });
  fireEvent.click(screen.getByRole("button", { name: "Submit Review" }));
  expect(screen.getByRole("alert").textContent).toMatch(/10 and 1000/);
  expect(submitProjectReview).not.toHaveBeenCalled();
  vi.mocked(submitProjectReview).mockRejectedValue(new Error("Too many review submissions. Please try again later."));
  fireEvent.change(screen.getByLabelText("Review (required)"), { target: { value: review.reviewText } });
  fireEvent.click(screen.getByRole("button", { name: "Submit Review" }));
  await waitFor(() => expect(screen.getByRole("alert").textContent).toMatch(/Too many/));
 });
 it("submits once, disables all inputs while pending, reloads visible summary and resets fields", async () => {
  let resolve!: (value: typeof review) => void;
  vi.mocked(submitProjectReview).mockImplementation(() => new Promise((done) => { resolve = done; }));
  render(<ProjectReviews projectId="project-1" />);
  await screen.findByText(/No reviews yet/);
  fireEvent.change(screen.getByLabelText("Your Name (required)"), { target: { value: " Visitor " } });
  fireEvent.click(screen.getByRole("radio", { name: "5 stars" }));
  fireEvent.change(screen.getByLabelText("Review (required)"), { target: { value: " "+review.reviewText+" " } });
  const form=screen.getByRole("form",{name:"Write a Review"});
  fireEvent.submit(form); fireEvent.submit(form);
  expect(submitProjectReview).toHaveBeenCalledTimes(1);
  expect(submitProjectReview).toHaveBeenCalledWith("project-1", {reviewerName:"Visitor",rating:5,reviewText:review.reviewText},expect.any(AbortSignal));
  expect((screen.getByLabelText("Your Name (required)") as HTMLInputElement).matches(":disabled")).toBe(true);
  vi.mocked(fetchProjectReviews).mockResolvedValue({reviews:[review],reviewCount:1,averageRating:5,hasMore:false});
  resolve(review);
  expect(await screen.findByText(review.reviewText)).toBeDefined();
  expect(await screen.findByText("Based on 1 review")).toBeDefined();
  expect((screen.getByLabelText("Your Name (required)") as HTMLInputElement).value).toBe("");
  expect(screen.getByRole("radio",{name:"5 stars"}).getAttribute("checked")).toBeNull();
  expect(screen.getByText(/Thank you!/)).toBeDefined();
 });
 it("uses native keyboard star selection and keeps plain review text escaped", async () => {
  const user=userEvent.setup();
  vi.mocked(fetchProjectReviews).mockResolvedValue({reviews:[{...review,reviewText:"<script>alert('x')</script>"}],reviewCount:1,averageRating:5,hasMore:false});
  const {container}=render(<ProjectReviews projectId="project-1" />);
  await screen.findByText("<script>alert('x')</script>");
  expect(container.querySelector("script")).toBeNull();
  const star=screen.getByRole("radio",{name:"1 star"});
  star.focus(); await user.keyboard("[ArrowRight]");
  expect((screen.getByRole("radio",{name:"2 stars"}) as HTMLInputElement).checked).toBe(true);
 });
 it("paginates reviews while preserving totals, and exposes a retry on fetch failure", async () => {
  vi.mocked(fetchProjectReviews).mockRejectedValueOnce(new Error("Unavailable")).mockResolvedValue({reviews:[review],reviewCount:25,averageRating:4.8,hasMore:true});
  render(<ProjectReviews projectId="project-1" />);
  fireEvent.click(await screen.findByRole("button",{name:"Retry reviews"}));
  expect(await screen.findByText("Based on 25 reviews")).toBeDefined();
  fireEvent.click(screen.getByRole("button",{name:"Next reviews"}));
  await waitFor(()=>expect(fetchProjectReviews).toHaveBeenLastCalledWith("project-1",2,expect.any(AbortSignal)));
 });
 it("aborts previous requests and resets reviews and form when the modal changes project", async () => {
  const project: PublicProject={id:"project-1",title:"Solar",slug:"solar",category:"Electrical Works",completionYear:2026,completionDate:"2026-09-15",images:[],mainImage:null,fullStory:"Engineering story.",clientOrganization:null,location:null,size:null,shortSummary:null,description:null,equipment:[],status:"published",isFeaturedHomepage:false,homepageOrder:null,publishedAt:null,createdAt:review.createdAt,updatedAt:review.createdAt};
  const {rerender}=render(<ProjectDetailModal project={project} onClose={()=>{}}/>);
  expect(screen.getByText("Completed 15 September 2026")).toBeDefined();
  await screen.findByText(/No reviews yet/);
  const oldSignal=vi.mocked(fetchProjectReviews).mock.calls[0][2];
  fireEvent.change(screen.getByLabelText("Your Name (required)"),{target:{value:"Unsubmitted"}});
  rerender(<ProjectDetailModal project={{...project,id:"project-2"}} onClose={()=>{}}/>);
  await waitFor(()=>expect(fetchProjectReviews).toHaveBeenLastCalledWith("project-2",1,expect.any(AbortSignal)));
  expect(oldSignal?.aborted).toBe(true);
  expect((screen.getByLabelText("Your Name (required)") as HTMLInputElement).value).toBe("");
 });
 it("formats exact dates consistently and preserves legacy years without inventing dates", () => {
  expect(formatProjectCompletion({completionDate:"2026-09-15",completionYear:2025})).toBe("15 September 2026");
  expect(formatProjectCompletion({completionDate:null,completionYear:2026})).toBe("2026");
  expect(formatProjectCompletion({completionDate:null,completionYear:null})).toBeNull();
 });
 it("Admin hides, restores and only permanently deletes after confirmation", async () => {
  const user=userEvent.setup(); const adminReview={...review,isVisible:true,updatedAt:review.createdAt};
  vi.mocked(fetchAdminProjectReviews).mockResolvedValue({reviews:[adminReview],hasMore:false});
  vi.mocked(setAdminReviewVisibility).mockResolvedValueOnce({...adminReview,isVisible:false}).mockResolvedValueOnce(adminReview);
  vi.mocked(deleteAdminReview).mockResolvedValue();
  render(<ProjectReviewsManager projectId="project-1" />);
  await user.click(await screen.findByRole("button",{name:"Hide"}));
  expect(setAdminReviewVisibility).toHaveBeenCalledWith("review-1",false);
  await user.click(await screen.findByRole("button",{name:"Show"}));
  expect(setAdminReviewVisibility).toHaveBeenLastCalledWith("review-1",true);
  await user.click(screen.getByRole("button",{name:"Delete permanently"}));
  expect(deleteAdminReview).not.toHaveBeenCalled();
  await user.click(screen.getByRole("button",{name:"Cancel"}));
  expect(screen.queryByRole("button",{name:"Confirm permanent deletion"})).toBeNull();
  await user.click(screen.getByRole("button",{name:"Delete permanently"}));
  vi.mocked(fetchAdminProjectReviews).mockResolvedValue({reviews:[],hasMore:false});
  await user.click(screen.getByRole("button",{name:"Confirm permanent deletion"}));
  expect(deleteAdminReview).toHaveBeenCalledWith("review-1");
  expect(await screen.findByText("No reviews yet.")).toBeDefined();
 });
});
