export const siteConfig = {
  company: "Electro Tech",
  descriptor: "Electrical & Solar Solutions",
  established: "2019",
  siteUrl: "https://electrotech-attock.com",
  phoneDisplay: "+92 3105056394",
  phoneHref: "tel:+923105056394",
  whatsappNumber: "923105056394",
  whatsappHref:
    "https://wa.me/923105056394?text=Hello%20Electro%20Tech%2C%20I%20would%20like%20to%20discuss%20a%20solar%20or%20electrical%20project.",
  email: "aqeel@electrotech-attock.com",
  services: [
    "Solar Energy",
    "Solar Structures",
    "Electrical Works",
    "Security Systems",
    "Other Project Enquiry",
  ],
  projects: [
    {
      id: "bilal-pharmacy",
      title: "Bilal Pharmacy", location: "Attock", size: null, description: null,
      primaryImage: "/images/solar-rooftop.webp",
      secondaryImage: "/images/hero-solar-architectural.webp",
    },
    { title: "Haji and Sons Medicine Pharma" },
    {
      id: "ahsan-pharmacy",
      title: "Ahsan Pharmacy", location: "Hazro", size: null, description: null,
      primaryImage: "/images/hero-solar.webp",
      secondaryImage: "/images/solar-energy-solutions.webp",
    },
    {
      id: "green-wood-school",
      title: "Green Wood School", location: "3 Meela, Attock", size: null, description: null,
      primaryImage: "/images/solar-technician.webp",
      secondaryImage: "/images/commercial-solar.webp",
      secondaryImagePosition: "center bottom",
    },
    { title: "Quaid-e-Azam Model School" },
    {
      id: "punjab-ice-factory", featured: true,
      title: "Punjab Ice Factory", location: "Saddar Road, Attock Cantt", size: "6 kW Hybrid",
      description: "6 kW Hybrid solar system installed inside Punjab Ice Factory.",
      equipment: ["SAJ inverter", "12 solar panels", "Aiko and Canadian solar panels"],
      primaryImage: "/images/projects/punjab-ice-factory-attock-01.webp",
      secondaryImage: "/images/projects/punjab-ice-factory-attock-02.webp",
      primaryAlt: "Solar panel array at Punjab Ice Factory, Attock Cantt",
      secondaryAlt: "Side view of the solar array and support structure at Punjab Ice Factory",
    },
    {
      id: "she-shelter-girls-hostel", featured: true,
      title: "She Shelter Girls Hostel", location: "Opposite DHQ, Attock",
      size: "12 kW Hybrid + 20 kW Lithium Battery Backup",
      description: "12 kW Hybrid Solar System with lithium battery backup for She Shelter Girls Hostel opposite DHQ Attock.",
      equipment: ["Itel 12 kW Single Phase", "PV 16000", "4 × batteries", "Each battery: 5 kW, 51 Volt, 100 Ah", "24 × Aiko solar panels", "Panel rating: 665 watt"],
      primaryImage: "/images/projects/she-shelter-girls-hostel-attock-01.webp",
      secondaryImage: "/images/projects/she-shelter-girls-hostel-attock-02.webp",
      primaryImagePosition: "center 65%",
      primaryAlt: "Elevated rooftop solar panels at She Shelter Girls Hostel in Attock",
      secondaryAlt: "Rows of rooftop solar panels at She Shelter Girls Hostel",
    },
    {
      id: "sabir-house", featured: true,
      title: "Mr Sabir House", location: "Madni Colony, Street No. 8, Attock", size: "4 kW Hybrid",
      description: "Residential 4 kW Hybrid Solar System installed at Mr Sabir's house in Madni Colony.",
      equipment: ["4 kW Hybrid Solar System", "2.5 kW lithium battery", "Battery: 25 Volt, 100 Ah", "6 × Aiko solar panels", "Panel rating: 665 watt"],
      primaryImage: "/images/projects/sabir-house-madni-colony-01.webp",
      secondaryImage: "/images/projects/sabir-house-madni-colony-02.webp",
      secondaryImagePosition: "center 65%",
      primaryAlt: "Rooftop solar panels at Mr Sabir's house in Madni Colony",
      secondaryAlt: "Wall-mounted inverter, battery and electrical equipment at Mr Sabir's house",
    },
    {
      id: "iqbal-malik-house", featured: true,
      title: "Mr Iqbal Malik House", location: "Mehria Town, Dua Chowk, Attock City", size: "10 kW On-Grid + 6 kW Hybrid",
      description: "Combined On-Grid and Hybrid solar installation at Mr Iqbal Malik's residence in Mehria Town.",
      equipment: ["10 kW On-Grid Solar System", "10 kW Knox On-Grid Three-Phase inverter", "6 kW Knox Hybrid Solar System", "5 kW lithium battery", "Battery: 51 Volt, 100 Ah", "H-Beam structure", "22 × Astro Energy solar panels", "Client-provided panel rating: 585"],
      primaryImage: "/images/projects/iqbal-malik-house-mehria-town-01.webp",
      secondaryImage: "/images/projects/iqbal-malik-house-mehria-town-02.webp",
      primaryAlt: "Elevated solar panels above Mr Iqbal Malik's residence in Mehria Town",
      secondaryAlt: "Solar panel support structure viewed from below at Mr Iqbal Malik's house",
    },
    {
      id: "saddar-bazar-fronus", featured: true,
      title: "Saddar Bazar Fronus Solar System", location: "Saddar Bazar, Attock", size: "6 kW Solar System",
      description: "6 kW solar setup using Fronus equipment in Saddar Bazar, Attock.",
      equipment: ["6 kW setup", "Fronus", "7 × Aiko solar panels", "Panel rating: 665 watts"],
      primaryImage: "/images/projects/saddar-bazar-attock-fronus-01.webp",
      secondaryImage: "/images/projects/saddar-bazar-attock-fronus-02.webp",
      primaryAlt: "Rooftop solar installation in Saddar Bazar, Attock",
      secondaryAlt: "Close view of the solar panels at the Saddar Bazar Fronus installation",
    },
    {
      id: "syed-mozaam-house", featured: true,
      title: "Mr Syed Mozaam House", location: "Mehria Town, Street No. 6, Attock City", size: "10 kW On-Grid + 4 kW Hybrid",
      description: "Combined On-Grid and Hybrid residential solar system at Mr Syed Mozaam's house in Mehria Town.",
      equipment: ["10 kW On-Grid Three-Phase Itel inverter", "4 kW Hybrid Solar System", "2.5 kW lithium battery", "Battery: 25 Volt, 100 Ah", "18 × Canadian solar panels", "585 watt", "N-Type Bifacial", "H-Beam structure"],
      primaryImage: "/images/projects/syed-mozaam-house-mehria-town-01.webp",
      secondaryImage: "/images/projects/syed-mozaam-house-mehria-town-02.webp",
      secondaryImagePosition: "center 35%",
      primaryAlt: "Elevated rooftop solar array at Mr Syed Mozaam's house in Mehria Town",
      secondaryAlt: "Wall-mounted solar inverters, battery and distribution equipment at Mr Syed Mozaam's house",
    },
    {
      id: "darul-islam-colony", featured: true,
      title: "Darul Islam Colony Solar Project", location: "Near Alkhiat Hospital, Darul Islam Colony, Attock City", size: "8 kW Hybrid",
      description: "8 kW Hybrid Solar System installed near Alkhiat Hospital in Darul Islam Colony, Attock City.",
      equipment: ["8 kW Hybrid Solar System", "8 kW Core Tech Hybrid Solar Inverter", "IP66 inverter", "5 kW INVT Lithium Battery", "Battery: 51 Volt, 100 Ah", "14 × LONGi Hi-MO X10 solar panels", "H-Beam structure"],
      primaryImage: "/images/projects/darul-islam-colony-attock-01.webp",
      secondaryImage: "/images/projects/darul-islam-colony-attock-02.webp",
      primaryImagePosition: "center 60%",
      primaryAlt: "Rooftop solar array near Alkhiat Hospital in Darul Islam Colony",
      secondaryAlt: "Solar panels and H-Beam support structure at the Darul Islam Colony installation",
    },
  ],
  technologies: ["Inverex", "Solis", "Tesla", "Growatt", "Core Tech", "Itel"],
} as const;

export type ServiceName = (typeof siteConfig.services)[number];
